### ISSUE TITLE
Theme not available in settings

### ISSUE THREAD

**Issue by Jenack** [kleber-swf/vscode-ocean-dark-extended-theme#2]
After having installed the theme through the marketplace, it does not show up as an option to pick from the theme color menu as shown:

![Issue](https://image.prntscr.com/image/cWbubyOsQ9e-9x-3FwL2AA.png)

**Comment by kleber-swf** [comment]
It's "Ocean Dark Extended".
Sorry for the confusion :sweat_smile:
